import "server-only";
// scripts/.id-map-3ba.json is generated by scripts/seed-3ba.mjs (or
// scripts/derive-id-map-3ba.mjs). It is the SINGLE source of truth for slug
// derivation — this bridge never runs slugify itself.
//
// 3b-A: Listing.areaId / Listing.agentId still carry legacy seed string ids.
// RSCs use these helpers to translate to the slug, then fetch the row from
// Supabase. The whole bridge is deleted in 3b-B-3 once every reference is a
// UUID. (The listing legacy helpers were removed in 3b-B-2 — favourites /
// recent_views now store the listing UUID directly, see migration 0008.)
import idMap from "@/scripts/.id-map-3ba.json";

interface MapEntry {
  uuid: string;
  slug: string;
}

const AREAS = idMap.areas as Record<string, MapEntry>;
const AGENTS = idMap.agents as Record<string, MapEntry>;

export function areaSlugForLegacyId(legacyId: string): string | null {
  return AREAS[legacyId]?.slug ?? null;
}

export function agentSlugForLegacyId(legacyId: string): string | null {
  return AGENTS[legacyId]?.slug ?? null;
}

export function areaUuidForLegacyId(legacyId: string): string | null {
  return AREAS[legacyId]?.uuid ?? null;
}

export function agentUuidForLegacyId(legacyId: string): string | null {
  return AGENTS[legacyId]?.uuid ?? null;
}
