import type { Area } from "@/lib/types";

export const AREAS: Area[] = [
  {
    id: "bangsar",
    name: "Bangsar",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1290,
    lng: 101.6700,
    nearbyUniversityIds: ["um"],
    vibe: "Cafés, walkable, expat-friendly",
  },
  {
    id: "pantai-dalam",
    name: "Pantai Dalam",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1130,
    lng: 101.6680,
    nearbyUniversityIds: ["um"],
    vibe: "Quiet, near UM back gate",
  },
  {
    id: "pj",
    name: "Petaling Jaya",
    city: "Petaling Jaya",
    state: "Selangor",
    lat: 3.1073,
    lng: 101.6067,
    nearbyUniversityIds: ["um", "taylors", "sunway", "monash"],
    vibe: "Mature suburb, good transit",
  },
  {
    id: "bangi",
    name: "Bangi",
    city: "Bangi",
    state: "Selangor",
    lat: 2.9436,
    lng: 101.7847,
    nearbyUniversityIds: ["ukm"],
    vibe: "Student town, halal food",
  },
  {
    id: "serdang",
    name: "Seri Kembangan / Serdang",
    city: "Seri Kembangan",
    state: "Selangor",
    lat: 3.0260,
    lng: 101.7100,
    nearbyUniversityIds: ["upm"],
    vibe: "Mixed, hawker food",
  },
  {
    id: "cyberjaya",
    name: "Cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    lat: 2.9213,
    lng: 101.6559,
    nearbyUniversityIds: ["mmu"],
    vibe: "Tech hub, modern condos",
  },
  {
    id: "shah-alam",
    name: "Shah Alam Section 7",
    city: "Shah Alam",
    state: "Selangor",
    lat: 3.0710,
    lng: 101.5050,
    nearbyUniversityIds: ["uitm"],
    vibe: "Lively, near UiTM",
  },
  {
    id: "subang-jaya",
    name: "Subang Jaya / SS15",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0750,
    lng: 101.5910,
    nearbyUniversityIds: ["sunway", "taylors", "monash"],
    vibe: "Bubble tea capital, busy",
  },
  {
    id: "bandar-sunway",
    name: "Bandar Sunway",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0660,
    lng: 101.6035,
    nearbyUniversityIds: ["sunway", "monash", "taylors"],
    vibe: "Canopy walk to campus",
  },
  {
    id: "cheras",
    name: "Cheras",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.0830,
    lng: 101.7400,
    nearbyUniversityIds: ["ucsi"],
    vibe: "Affordable, MRT access",
  },
  {
    id: "gombak",
    name: "Gombak",
    city: "Gombak",
    state: "Selangor",
    lat: 3.2480,
    lng: 101.7340,
    nearbyUniversityIds: ["iium"],
    vibe: "Hilly, close to IIUM",
  },
  {
    id: "setapak",
    name: "Setapak",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1980,
    lng: 101.7150,
    nearbyUniversityIds: ["iium"],
    vibe: "Student-dense, malls nearby",
  },
];

export const AREA_BY_ID = Object.fromEntries(
  AREAS.map((a) => [a.id, a]),
) as Record<string, Area>;
