import type { Listing } from "@/lib/types";

// Script-only seed data (LC-09). Phase 4c-B1: photos no longer live here — the
// seed script (scripts/seed-3bb1.mjs) re-hosts a demo image pool into the
// listing-photos bucket and writes listing_photos rows; the legacy
// listings.photos column is dropped (migration 0017). So the seed object omits
// photos, and is typed as Listing-without-photos.
type SeedListing = Omit<Listing, "photos">;

export const LISTINGS: SeedListing[] = [
  {
    id: "lst-001",
    slug: "cosy-studio-bangsar-near-um",
    title: "Cosy studio in Bangsar, walk to UM",
    type: "studio",
    status: "available",
    priceMonthly: 1450,
    deposit: 2900,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 420,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-01",
    minStayMonths: 6,
    address: "Jalan Maarof, Bangsar",
    areaId: "bangsar",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1290,
    lng: 101.6700,
    nearbyUniversityIds: ["um"],
    walkMinsToCampus: 18,
    metresToCampus: 1800,
    amenities: ["wifi", "aircon", "washer", "kitchen", "parking"],
    description:
      "A bright, fully-furnished studio on the 3rd floor of a low-rise walk-up off Jalan Maarof. Hardwood-look flooring throughout, a queen bed with new mattress, a study desk facing the window, a kitchenette with induction hob, and a private bathroom with water heater. The unit is air-conditioned in both the bed and study area.\n\nBangsar Village and Bangsar Shopping Centre are a 6-minute walk through Lucky Garden, with the Bangsar LRT station 8 minutes on foot. UM's Faculty of Arts gate is roughly 1.8 km — most students Grab in (RM 6) or take the U86 feeder bus from Bangsar LRT, which terminates at the UM main library.\n\nThe block has 1 covered car park lot included, 24-hour guard, and a small rooftop laundry. Cafés on Jalan Telawi are 5 minutes walk; the closest 24-hour Mamak is Devi's Corner. Quiet on weekday nights, busier on Friday and Saturday.",
    agentId: "agent-aisha",
    rating: 4.7,
    reviewCount: 23,
    createdAt: "2026-04-01",
    updatedAt: "2026-04-20",
  },
  {
    id: "lst-002",
    slug: "single-room-pantai-dalam-um",
    title: "Single room near UM back gate",
    type: "room",
    status: "available",
    priceMonthly: 650,
    deposit: 1300,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 140,
    furnishing: "partial",
    genderPreference: "female",
    availableFrom: "2026-05-15",
    minStayMonths: 4,
    address: "Pangsapuri Sri Pantai, Pantai Dalam",
    areaId: "pantai-dalam",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1130,
    lng: 101.6680,
    nearbyUniversityIds: ["um"],
    walkMinsToCampus: 8,
    metresToCampus: 600,
    amenities: ["wifi", "aircon", "shared-kitchen"],
    description:
      "Female-only single room in a 4-bedroom unit at Pangsapuri Sri Pantai, on the Pantai Dalam side of UM. The room comes with a single bed, study desk, wardrobe, and ceiling fan. Air conditioning is in the room (shared electricity bill, capped at RM 80/month). Sheets and pillow provided.\n\nThe Pantai Dalam back gate of UM is a 600 m walk through the residential lane behind Jalan Pantai Murni — about 8 minutes door-to-faculty. Pantai Dalam KTM is 12 minutes on foot for trips to Mid Valley or KL Sentral.\n\nThe unit is shared with three other UM students (Year 2 and 3, all female). Common areas include a kitchen with shared fridge and rice cooker, a living room with TV, and a small balcony with a clothesline. Speedmart 99 is at the corner, and the row of food stalls in front of UM Hospital is a 5-minute walk.",
    agentId: "agent-aisha",
    rating: 4.4,
    reviewCount: 11,
    featured: true,
    createdAt: "2026-03-12",
    updatedAt: "2026-04-18",
  },
  {
    id: "lst-003",
    slug: "shared-house-bangi-ukm",
    title: "Shared house, 5 mins to UKM",
    type: "house",
    status: "available",
    priceMonthly: 550,
    deposit: 1100,
    utilitiesIncluded: false,
    bedrooms: 4,
    bathrooms: 3,
    sizeSqft: 1800,
    furnishing: "partial",
    genderPreference: "male",
    availableFrom: "2026-07-01",
    minStayMonths: 12,
    address: "Taman Tasik Semenyih, Bangi",
    areaId: "bangi",
    city: "Bangi",
    state: "Selangor",
    lat: 2.9436,
    lng: 101.7847,
    nearbyUniversityIds: ["ukm"],
    walkMinsToCampus: 6,
    metresToCampus: 450,
    amenities: ["wifi", "parking", "garden", "kitchen"],
    description:
      "A double-storey terrace house in Taman Tasik Semenyih with four bedrooms, three bathrooms, a fitted kitchen, living room, and a small back garden. Single beds with study desks in each room, fans, and partial wardrobes; tenants typically add their own air-conditioning units (sockets ready). Two covered parking lots in front.\n\nThe house is 5 minutes' walk to UKM's main gate via Jalan 7/4D, and 8 minutes by car to Bangi KTM station. The neighbourhood is quiet, mostly families and final-year students, with a 24-hour Mamak two doors down and a Speedmart 99 at the corner of Jalan 7/4.\n\nThe house is shared with three other UKM students (all male, two engineering and one law in their final year). Common areas include the kitchen, living room with TV, washing machine, and the back garden with a clothesline. Bangi Gateway Mall is a 6-minute drive (or RM 5 Grab), and the UKM hospital is 1.4 km away for any walk-in clinic visits.",
    agentId: "agent-faiz",
    rating: 4.5,
    reviewCount: 18,
    featured: true,
    createdAt: "2026-02-22",
    updatedAt: "2026-04-15",
  },
  {
    id: "lst-004",
    slug: "studio-cyberjaya-mmu",
    title: "Modern studio in Cyberjaya",
    type: "studio",
    status: "available",
    priceMonthly: 1100,
    deposit: 2200,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 480,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-15",
    minStayMonths: 6,
    address: "D'Pulze Residence, Cyberjaya",
    areaId: "cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    lat: 2.9213,
    lng: 101.6559,
    nearbyUniversityIds: ["mmu"],
    walkMinsToCampus: 12,
    metresToCampus: 950,
    amenities: ["wifi", "aircon", "pool", "gym", "parking"],
    description:
      "A modern fully-furnished studio in D'Pulze Residence, Cyberjaya. The unit comes with a queen bed, built-in wardrobe, study area, kitchenette with induction hob and microwave, and a glass-screen shower bathroom. Air-conditioning, ceiling fan, smart TV, and 300 Mbps fibre wifi included.\n\nMMU's main entrance is a 12-minute walk through the linkway behind D'Pulze Mall, or 4 minutes by Cyberjaya Smart Bus (free for students). Tamarind Square and the new Cyberjaya City Centre MRT are within 10 minutes by car. The campus shuttle picks up directly at the lobby on weekdays.\n\nResidence amenities include a 25 m infinity pool, gym, co-working lounge, and 24-hour security with biometric access. Below the building you'll find Family Mart, a Starbucks, and three coffee shops. Maintenance and one parking bay are included; electricity bill averages RM 90/month with daily aircon use.",
    agentId: "agent-priya",
    rating: 4.8,
    reviewCount: 34,
    createdAt: "2026-03-30",
    updatedAt: "2026-04-22",
  },
  {
    id: "lst-005",
    slug: "apartment-subang-sunway-monash",
    title: "2-bed apartment, walk to Sunway & Monash",
    type: "apartment",
    status: "available",
    priceMonthly: 2200,
    deposit: 4400,
    utilitiesIncluded: false,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 850,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-01",
    minStayMonths: 12,
    address: "Geo Avenue, Bandar Sunway",
    areaId: "bandar-sunway",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0660,
    lng: 101.6035,
    nearbyUniversityIds: ["sunway", "monash", "taylors"],
    walkMinsToCampus: 6,
    metresToCampus: 500,
    amenities: ["wifi", "aircon", "pool", "gym", "parking", "security"],
    description:
      "A premium 2-bedroom 2-bathroom apartment at Geo Avenue, directly facing Sunway University across the canopy walk. Both bedrooms are ensuite with queen beds, built-in wardrobes, and individual aircon. The living-dining area opens onto a balcony with a view of Sunway Lagoon.\n\nThe canopy walk to Sunway University takes 6 minutes; Monash University Malaysia is a further 4 minutes, and Taylor's Lakeside is 12 minutes by Sunway BRT. Sunway Pyramid is connected via the same canopy and is a 7-minute walk. The Sunway-Setia Jaya BRT station is 2 minutes from the lobby.\n\nFully serviced building: 50 m pool, gym, sauna, multipurpose hall, and 24-hour concierge with parcel lockers. Two covered parking bays included. Maintenance fee is paid by the landlord; tenants cover electricity (avg RM 180/month for two), water, and TNB.",
    agentId: "agent-mei",
    rating: 4.9,
    reviewCount: 47,
    featured: true,
    listedToday: true,
    createdAt: "2026-04-05",
    updatedAt: "2026-04-25",
  },
  {
    id: "lst-006",
    slug: "room-ss15-taylors",
    title: "Room in SS15 condo near Taylor's",
    type: "room",
    status: "available",
    priceMonthly: 850,
    deposit: 1700,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 160,
    furnishing: "full",
    genderPreference: "female",
    availableFrom: "2026-05-20",
    minStayMonths: 6,
    address: "SS15 Courtyard, Subang Jaya",
    areaId: "subang-jaya",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0750,
    lng: 101.5910,
    nearbyUniversityIds: ["taylors", "sunway"],
    walkMinsToCampus: 10,
    metresToCampus: 800,
    amenities: ["wifi", "aircon", "pool", "gym", "shared-kitchen"],
    description:
      "Female-only room in a 3-bedroom condo on the 18th floor of SS15 Courtyard. The room is fully furnished — single bed with new mattress, built-in wardrobe, study desk, swivel chair, and own air-conditioner with remote. Utilities are capped at RM 100/month.\n\nThe SS15 LRT station is 4 minutes' walk via the covered linkway. Taylor's Lakeside is one stop away (8 minutes door-to-door including the walk), Sunway University is 12 minutes by feeder bus, and SEGi College is 6 minutes on foot. The bubble tea row on Jalan SS15/4 is right at the lobby.\n\nThe condo is shared with two other Taylor's students (Year 2 and 3, all female). Shared kitchen with rice cooker, fridge, induction hob, and washer-dryer. Building amenities: 30 m pool, gym, reading room, and 24-hour security. Family Mart and Speedmart 99 are at street level.",
    agentId: "agent-mei",
    rating: 4.6,
    reviewCount: 29,
    createdAt: "2026-03-18",
    updatedAt: "2026-04-19",
  },
  {
    id: "lst-007",
    slug: "studio-cheras-ucsi",
    title: "Studio next to UCSI",
    type: "studio",
    status: "available",
    priceMonthly: 1250,
    deposit: 2500,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 450,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-10",
    minStayMonths: 6,
    address: "You Vista, Cheras",
    areaId: "cheras",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.0770,
    lng: 101.7320,
    nearbyUniversityIds: ["ucsi"],
    walkMinsToCampus: 5,
    metresToCampus: 400,
    amenities: ["wifi", "aircon", "pool", "gym", "parking"],
    description:
      "Brand-new fully-furnished studio in You Vista, the closest serviced apartment to UCSI University. Queen bed, walk-in wardrobe, kitchenette with induction hob, glass-screen shower, and a 4 m balcony overlooking the UCSI sports field. All-in aircon, smart TV, and 500 Mbps wifi.\n\nUCSI's main building is a 5-minute walk via the dedicated student bridge (no traffic crossings). Taman Connaught MRT is 8 minutes on foot, and Cheras Sentral mall is one MRT stop away. The Pasar Malam on Tuesday nights at Connaught is a Cheras institution — RM 1 char kway teow, plenty of seating.\n\nBuilding amenities include a 25 m pool, gym, co-working space, and 24-hour security with facial recognition. One covered parking bay included. Below the building: Family Mart, a Starbucks, and a row of late-night kopitiams. Electricity averages RM 110/month with daily aircon.",
    agentId: "agent-ben",
    rating: 4.7,
    reviewCount: 22,
    featured: true,
    listedToday: true,
    createdAt: "2026-04-02",
    updatedAt: "2026-04-23",
  },
  {
    id: "lst-008",
    slug: "room-gombak-iium",
    title: "Quiet room 10 mins from IIUM",
    type: "room",
    status: "available",
    priceMonthly: 480,
    deposit: 960,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 130,
    furnishing: "partial",
    genderPreference: "male",
    availableFrom: "2026-05-25",
    minStayMonths: 4,
    address: "Taman Greenwood, Gombak",
    areaId: "gombak",
    city: "Gombak",
    state: "Selangor",
    lat: 3.2480,
    lng: 101.7340,
    nearbyUniversityIds: ["iium"],
    walkMinsToCampus: 22,
    metresToCampus: 1700,
    amenities: ["wifi", "shared-kitchen", "parking"],
    description:
      "Male-only single room in a single-storey terrace house in Taman Greenwood, Gombak. The room has a single bed, built-in wardrobe, study desk, ceiling fan, and a window facing the back lane. Tenants share a bathroom with one other student. Utilities, wifi, and Astro included in rent.\n\nIIUM's Gombak gate is roughly 1.7 km — about 22 minutes on foot or a 5-minute Grab (RM 4-5). The free IIUM shuttle picks up at Greenwood Square (3 minutes' walk from the house) every 20 minutes from 7am to 8pm on weekdays. Gombak LRT terminus is 1.2 km away for trips into the city.\n\nThe house is shared with two other IIUM students (Year 2 and Year 4, both male). Common kitchen has a fridge, kettle, rice cooker, and a small dining table. The 99 Speedmart is 220 m down the road, and Restoran Anjung Selera serves nasi lemak from 6am. Quiet residential area with mostly families.",
    agentId: "agent-arif",
    rating: 4.3,
    reviewCount: 9,
    createdAt: "2026-02-28",
    updatedAt: "2026-04-12",
  },
  {
    id: "lst-009",
    slug: "apartment-shah-alam-uitm",
    title: "3-bed apartment in Shah Alam Sec 7",
    type: "apartment",
    status: "available",
    priceMonthly: 1800,
    deposit: 3600,
    utilitiesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqft: 1100,
    furnishing: "partial",
    genderPreference: "mixed",
    availableFrom: "2026-07-01",
    minStayMonths: 12,
    address: "Section 7, Shah Alam",
    areaId: "shah-alam",
    city: "Shah Alam",
    state: "Selangor",
    lat: 3.0710,
    lng: 101.5050,
    nearbyUniversityIds: ["uitm"],
    walkMinsToCampus: 14,
    metresToCampus: 1100,
    amenities: ["wifi", "aircon", "parking", "kitchen"],
    description:
      "A 3-bedroom 2-bathroom corner apartment on the 8th floor of a Section 7 walk-up. Master bedroom with ensuite and queen bed; two single rooms each with built-in wardrobes and study desks. Living room with sofa and a 55-inch TV. Tiled kitchen with gas hob, fridge, and washing machine.\n\nUiTM Shah Alam main gate is 1.1 km — 14 minutes on foot via Persiaran Hijauan, or a 4-minute drive. Padang Jawa KTM is 6 minutes by car for trips into KL. Section 7 commercial centre — with cafés, Mamak, and the famous Subaidah — is 5 minutes' walk.\n\nGreat for three students sharing or a small family. Two covered parking bays included. Mydin Section 7 is 400 m for groceries, and Setia City Mall is 10 minutes by car. Electricity averages RM 220/month for three, water RM 30. The block has 24-hour guard and CCTV at the lifts.",
    agentId: "agent-faiz",
    rating: 4.5,
    reviewCount: 14,
    createdAt: "2026-03-08",
    updatedAt: "2026-04-17",
  },
  {
    id: "lst-010",
    slug: "studio-serdang-upm",
    title: "Studio near UPM main gate",
    type: "studio",
    status: "available",
    priceMonthly: 950,
    deposit: 1900,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 380,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-01",
    minStayMonths: 6,
    address: "Equine Park, Seri Kembangan",
    areaId: "serdang",
    city: "Seri Kembangan",
    state: "Selangor",
    lat: 3.0260,
    lng: 101.7100,
    nearbyUniversityIds: ["upm"],
    walkMinsToCampus: 15,
    metresToCampus: 1200,
    amenities: ["wifi", "aircon", "pool", "parking"],
    description:
      "A modern fully-furnished studio in Equine Park, Seri Kembangan, on the 12th floor with a clear view towards UPM. Queen bed, built-in wardrobe, study desk, kitchenette with induction hob, and a glass-screen shower bathroom. Aircon, ceiling fan, and 300 Mbps fibre wifi pre-installed.\n\nUPM's main gate is 1.2 km — 15 minutes on foot or a 4-minute drive. Serdang KTM station is 8 minutes by car (or 15 minutes by Rapid bus T580 from the lobby). Mines Shopping Mall is 2 km away, and the famous Serdang seafood restaurants on Jalan Serdang Utama are 10 minutes by Grab.\n\nResidence amenities include a 25 m pool, jogging track, and basement parking with one bay included. Below the building you'll find a 99 Speedmart, two kopitiams, and a Subway. The Equine area is mostly families and UPM postgrads — quiet on weekdays, busier on weekends with the night market on Sunday at Equine Park.",
    agentId: "agent-faiz",
    rating: 4.6,
    reviewCount: 17,
    createdAt: "2026-03-25",
    updatedAt: "2026-04-21",
  },
  {
    id: "lst-011",
    slug: "room-setapak-iium",
    title: "Female-only room in Setapak",
    type: "room",
    status: "reserved",
    priceMonthly: 720,
    deposit: 1440,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 150,
    furnishing: "full",
    genderPreference: "female",
    availableFrom: "2026-08-01",
    minStayMonths: 6,
    address: "Platinum Lake PV21, Setapak",
    areaId: "setapak",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1980,
    lng: 101.7150,
    nearbyUniversityIds: ["iium"],
    walkMinsToCampus: 30,
    metresToCampus: 4500,
    amenities: ["wifi", "aircon", "pool", "gym", "shared-kitchen"],
    description:
      "Female-only room on the 22nd floor of Platinum Lake PV21, Setapak. Furnished with a single bed (queen optional, +RM 50), built-in wardrobe, study desk, and own air-conditioner. Utilities, wifi, and Astro included. Private bathroom shared with one other female tenant.\n\nIIUM Gombak campus is 4.5 km away — best reached via the IIUM shuttle from Sri Rampai LRT (15 minutes including the walk to LRT) or Grab (RM 12-15). Sri Rampai LRT itself is 9 minutes' walk, with direct trips to KLCC and Wangsa Walk Mall.\n\nThe condo is shared with two other female students. Shared kitchen with fridge, induction hob, and a small dining nook. Building amenities include a 50 m pool, gym, sauna, sky lounge on the 30th floor, and 24-hour security with key card access. Setapak Central mall and the night market on Sundays are 8 minutes' walk.",
    agentId: "agent-ben",
    rating: 4.7,
    reviewCount: 31,
    createdAt: "2026-04-08",
    updatedAt: "2026-04-26",
  },
  {
    id: "lst-012",
    slug: "apartment-pj-um-monash",
    title: "Apartment in PJ, near UM and Monash",
    type: "apartment",
    status: "available",
    priceMonthly: 2400,
    deposit: 4800,
    utilitiesIncluded: false,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 920,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-15",
    minStayMonths: 12,
    address: "Section 17, Petaling Jaya",
    areaId: "pj",
    city: "Petaling Jaya",
    state: "Selangor",
    lat: 3.1073,
    lng: 101.6067,
    nearbyUniversityIds: ["um", "monash", "taylors"],
    walkMinsToCampus: 20,
    metresToCampus: 1500,
    amenities: ["wifi", "aircon", "pool", "gym", "parking", "security"],
    description:
      "A fully-furnished 2-bedroom 2-bathroom apartment in Section 17, Petaling Jaya. Both bedrooms are ensuite with queen beds and built-in wardrobes. Living-dining area with sofa, dining table for four, and a 55-inch TV. Tiled kitchen with gas hob, fridge, microwave, and full-size washer-dryer.\n\nUM Faculty of Engineering is 2.5 km (8 minutes by car); Monash MUM is 18 minutes by Federal Highway; Taylor's Lakeside is 22 minutes via NPE. Asia Jaya LRT is 8 minutes on foot via the residential lane behind Section 17 plaza. The Section 17 morning market is the best in PJ for fresh produce.\n\nServiced building with a 30 m pool, gym, sky lounge, and 24-hour concierge. Two covered parking bays included. Below the building: Jaya Shopping Centre, two banks, and a Cold Storage. Electricity averages RM 200/month for two with daily aircon use.",
    agentId: "agent-aisha",
    rating: 4.8,
    reviewCount: 40,
    createdAt: "2026-04-10",
    updatedAt: "2026-04-27",
  },
  {
    id: "lst-013",
    slug: "studio-cyberjaya-mmu-budget",
    title: "Budget studio in Cyberjaya",
    type: "studio",
    status: "available",
    priceMonthly: 850,
    deposit: 1700,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 350,
    furnishing: "partial",
    genderPreference: "mixed",
    availableFrom: "2026-05-30",
    minStayMonths: 4,
    address: "Cyberia SmartHomes, Cyberjaya",
    areaId: "cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    lat: 2.9213,
    lng: 101.6559,
    nearbyUniversityIds: ["mmu"],
    walkMinsToCampus: 18,
    metresToCampus: 1500,
    amenities: ["wifi", "pool", "parking"],
    description:
      "An affordable studio in Cyberia SmartHomes, one of Cyberjaya's older but well-maintained blocks. Partially furnished — single bed, study desk, wardrobe, ceiling fan (no aircon, but socket ready). Bathroom has a water heater. Tiled flooring throughout. Utilities and 100 Mbps wifi included.\n\nMMU Cyberjaya is 1.5 km — 18 minutes on foot, or 5 minutes by the free MMU shuttle that stops at the lobby every 30 minutes. Tamarind Square is a 4-minute walk for cafés and the weekend farmers' market. Cyberjaya City Centre MRT is 12 minutes by car.\n\nBlock amenities include a 20 m pool, basketball court, and one open-air parking bay. Below the building: a Mamak, two kopitiams, a Speedmart 99, and a coin laundry. Honest pricing for what you get — older fittings, but the layout is generous and the location works for MMU students on a budget.",
    agentId: "agent-priya",
    rating: 4.4,
    reviewCount: 19,
    createdAt: "2026-03-15",
    updatedAt: "2026-04-14",
  },
  {
    id: "lst-014",
    slug: "house-bangi-ukm-shared",
    title: "Female-only shared house in Bangi",
    type: "house",
    status: "available",
    priceMonthly: 600,
    deposit: 1200,
    utilitiesIncluded: false,
    bedrooms: 5,
    bathrooms: 3,
    sizeSqft: 2000,
    furnishing: "full",
    genderPreference: "female",
    availableFrom: "2026-07-15",
    minStayMonths: 12,
    address: "Bandar Baru Bangi",
    areaId: "bangi",
    city: "Bangi",
    state: "Selangor",
    lat: 2.9436,
    lng: 101.7847,
    nearbyUniversityIds: ["ukm"],
    walkMinsToCampus: 18,
    metresToCampus: 1400,
    amenities: ["wifi", "aircon", "kitchen", "parking", "garden"],
    description:
      "Female-only double-storey terrace house in Bandar Baru Bangi with five bedrooms and three bathrooms. Each room has a single bed, built-in wardrobe, study desk, and aircon. Living room with sofa and TV; tiled kitchen with gas hob, fridge, washing machine, and a back garden with a covered laundry area.\n\nUKM main gate is 1.4 km — 18 minutes on foot via Jalan 7/4, or 4 minutes by car. The free UKM shuttle stops at Bangi Sentral (5 minutes' walk from the house) every 15 minutes on weekdays. Bangi KTM is 10 minutes by car for trips into KL.\n\nShared by four other female UKM students (Year 2 to Year 4). House rules are simple — no overnight guests, weekly common-area cleaning roster. Two covered parking bays in front. Bangi Gateway Mall is 6 minutes by car, and there's a 24-hour Mamak two doors down.",
    agentId: "agent-faiz",
    rating: 4.6,
    reviewCount: 21,
    createdAt: "2026-03-05",
    updatedAt: "2026-04-16",
  },
  {
    id: "lst-015",
    slug: "studio-ss15-monash",
    title: "Premium studio steps from Monash",
    type: "studio",
    status: "available",
    priceMonthly: 1650,
    deposit: 3300,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 500,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-01",
    minStayMonths: 6,
    address: "Union Suites, Bandar Sunway",
    areaId: "bandar-sunway",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0660,
    lng: 101.6035,
    nearbyUniversityIds: ["monash", "sunway", "taylors"],
    walkMinsToCampus: 4,
    metresToCampus: 350,
    amenities: ["wifi", "aircon", "pool", "gym", "parking", "security"],
    description:
      "A premium high-floor studio in Union Suites, the newest serviced apartment in Bandar Sunway. Floor-to-ceiling windows facing Sunway Lagoon, queen bed, built-in wardrobe, designer kitchenette with induction hob and Bosch appliances, marble bathroom with rain shower. Smart home controls for aircon, lights, and curtains.\n\nMonash University Malaysia is 350 m via the Sunway canopy walk — 4 minutes door-to-faculty. Sunway University is 7 minutes by the same canopy. Sunway Pyramid is 5 minutes' walk, and Sunway-Setia Jaya BRT is 3 minutes from the lobby. Taylor's Lakeside is 10 minutes by feeder bus.\n\nFully serviced building: 50 m infinity pool on the 30th floor, gym, sauna, co-working lounge, sky garden, and concierge with parcel handling. One covered parking bay included. Family Mart and a Starbucks are at the lobby. Premium pricing reflects the location and finish — the listing is ideal for postgrad or working students.",
    agentId: "agent-mei",
    rating: 4.9,
    reviewCount: 53,
    createdAt: "2026-04-12",
    updatedAt: "2026-04-28",
  },
  {
    id: "lst-016",
    slug: "room-cheras-ucsi-budget",
    title: "Budget room near UCSI",
    type: "room",
    status: "available",
    priceMonthly: 550,
    deposit: 1100,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 120,
    furnishing: "partial",
    genderPreference: "mixed",
    availableFrom: "2026-05-15",
    minStayMonths: 4,
    address: "Taman Connaught, Cheras",
    areaId: "cheras",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.0830,
    lng: 101.7400,
    nearbyUniversityIds: ["ucsi"],
    walkMinsToCampus: 12,
    metresToCampus: 950,
    amenities: ["wifi", "shared-kitchen", "parking"],
    description:
      "Affordable single room in a Taman Connaught terrace house, mixed-gender share. Single bed, study desk, wardrobe, ceiling fan, window facing the back lane. Bathroom shared with one other tenant. Utilities, wifi, and Astro included. Tenants typically add their own aircon (socket ready).\n\nUCSI University is 950 m — 12 minutes on foot via the residential shortcut behind Jalan Cerdas, or 4 minutes by Grab. Taman Connaught MRT is 7 minutes' walk, with direct trips to TRX and KL Sentral. The Taman Connaught night market on Wednesdays is the best cheap eats in Cheras — RM 1 char kway teow, RM 2 satay.\n\nThe house has a fitted kitchen, living room with TV, and one open-air parking bay (allocated by sharing arrangement). Three other tenants — all UCSI students. Speedmart 99 is 110 m away, and the row of late-night kopitiams on Jalan Cerdas runs until 2am. Honest budget option for first-year students.",
    agentId: "agent-ben",
    rating: 4.2,
    reviewCount: 8,
    createdAt: "2026-02-18",
    updatedAt: "2026-04-10",
  },
  {
    id: "lst-017",
    slug: "apartment-shah-alam-uitm-premium",
    title: "Premium 2-bed near UiTM",
    type: "apartment",
    status: "available",
    priceMonthly: 1950,
    deposit: 3900,
    utilitiesIncluded: false,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 950,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-06-20",
    minStayMonths: 12,
    address: "i-City, Shah Alam",
    areaId: "shah-alam",
    city: "Shah Alam",
    state: "Selangor",
    lat: 3.0710,
    lng: 101.5050,
    nearbyUniversityIds: ["uitm"],
    walkMinsToCampus: 12,
    metresToCampus: 950,
    amenities: ["wifi", "aircon", "pool", "gym", "parking", "security"],
    description:
      "A premium fully-furnished 2-bedroom 2-bathroom apartment in i-City, Shah Alam. Both bedrooms are ensuite with queen beds, built-in wardrobes, and individual aircon. The living-dining area opens onto a balcony with a view of the i-City lights. Tiled kitchen with induction hob, fridge, microwave, and washer-dryer.\n\nUiTM Shah Alam is 950 m — 12 minutes on foot via the i-City pedestrian bridge, or 4 minutes by car. The free i-City shuttle to UiTM runs every 30 minutes on weekdays. Padang Jawa KTM is 8 minutes by car for trips into KL.\n\nServiced building with a 30 m pool, gym, theme park access (Snow Walk and Trick Art Museum at resident rate), and 24-hour concierge. Two covered parking bays included. Below the building: i-City Mall, Central i-City, Mercato supermarket, and over 30 restaurants. Electricity averages RM 200/month for two.",
    agentId: "agent-faiz",
    rating: 4.7,
    reviewCount: 26,
    createdAt: "2026-04-06",
    updatedAt: "2026-04-24",
  },
  {
    id: "lst-018",
    slug: "studio-bangsar-um-luxe",
    title: "Luxe studio in Bangsar South",
    type: "studio",
    status: "rented",
    priceMonthly: 1850,
    deposit: 3700,
    utilitiesIncluded: false,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqft: 520,
    furnishing: "full",
    genderPreference: "mixed",
    availableFrom: "2026-09-01",
    minStayMonths: 12,
    address: "The Establishment, Bangsar South",
    areaId: "bangsar",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1130,
    lng: 101.6680,
    nearbyUniversityIds: ["um"],
    walkMinsToCampus: 15,
    metresToCampus: 1200,
    amenities: ["wifi", "aircon", "pool", "gym", "parking", "security", "concierge"],
    description:
      "An upscale fully-furnished studio in The Establishment, Bangsar South. Designer-fitted kitchenette with marble countertops, queen bed with hotel-grade linen, walk-in wardrobe, rain-shower bathroom, and a 5 m balcony with a view of KL Eco City. Smart home controls, daily housekeeping option, and 1 Gbps fibre wifi.\n\nUM main gate is 1.2 km — 15 minutes on foot via the Bangsar South linkway, or 4 minutes by car. KL Sentral is two stops on the KTM from Pantai Dalam (10 minutes by Grab to Sentral). Mid Valley Megamall is 8 minutes by car. The Bangsar South food court (Nexus) has 25 stalls open till midnight.\n\nServiced building with a 50 m infinity pool, gym, sauna, sky lounge, and 24-hour concierge with valet parking. One covered parking bay included; second bay rentable at RM 200/month. Below the building: Family Mart, Starbucks Reserve, and a Common Man café. Currently rented through August 2026 — available from September 2026.",
    agentId: "agent-aisha",
    rating: 4.8,
    reviewCount: 38,
    createdAt: "2026-01-15",
    updatedAt: "2026-04-01",
  },
];

export const LISTING_BY_ID = Object.fromEntries(
  LISTINGS.map((l) => [l.id, l]),
) as Record<string, SeedListing>;
