import type { NearbyPOI } from "@/lib/types";

export const NEARBY_BY_AREA: Record<string, NearbyPOI[]> = {
  bangsar: [
    { name: "UM main gate", kind: "uni", distanceMetres: 1800 },
    { name: "Bangsar LRT", kind: "train", distanceMetres: 600 },
    { name: "Bangsar Village", kind: "mall", distanceMetres: 450 },
    { name: "Speedmart 99", kind: "mart", distanceMetres: 120 },
    { name: "Bukit Bandaraya Park", kind: "park", distanceMetres: 800 },
    { name: "Pantai Hospital KL", kind: "hospital", distanceMetres: 1500 },
  ],
  "pantai-dalam": [
    { name: "UM back gate", kind: "uni", distanceMetres: 600 },
    { name: "Pantai Dalam KTM", kind: "train", distanceMetres: 950 },
    { name: "Mid Valley Megamall", kind: "mall", distanceMetres: 2400 },
    { name: "99 Speedmart", kind: "mart", distanceMetres: 200 },
    { name: "UM Recreational Park", kind: "park", distanceMetres: 700 },
    { name: "UMMC", kind: "hospital", distanceMetres: 1100 },
  ],
  pj: [
    { name: "UM main gate", kind: "uni", distanceMetres: 3500 },
    { name: "Asia Jaya LRT", kind: "train", distanceMetres: 800 },
    { name: "Jaya Shopping Centre", kind: "mall", distanceMetres: 600 },
    { name: "Speedmart 99", kind: "mart", distanceMetres: 180 },
    { name: "Taman Jaya", kind: "park", distanceMetres: 900 },
    { name: "Assunta Hospital", kind: "hospital", distanceMetres: 1300 },
  ],
  bangi: [
    { name: "UKM main gate", kind: "uni", distanceMetres: 450 },
    { name: "Bangi KTM", kind: "train", distanceMetres: 2100 },
    { name: "Bangi Gateway Mall", kind: "mall", distanceMetres: 2800 },
    { name: "Speedmart 99", kind: "mart", distanceMetres: 90 },
    { name: "UKM Recreational Park", kind: "park", distanceMetres: 600 },
    { name: "UKM Hospital", kind: "hospital", distanceMetres: 1400 },
  ],
  serdang: [
    { name: "UPM main gate", kind: "uni", distanceMetres: 1200 },
    { name: "Serdang KTM", kind: "train", distanceMetres: 1700 },
    { name: "Mines Shopping Mall", kind: "mall", distanceMetres: 2200 },
    { name: "99 Speedmart", kind: "mart", distanceMetres: 150 },
    { name: "Mines Wellness Park", kind: "park", distanceMetres: 1800 },
    { name: "Serdang Hospital", kind: "hospital", distanceMetres: 2500 },
  ],
  cyberjaya: [
    { name: "MMU Cyberjaya", kind: "uni", distanceMetres: 900 },
    { name: "Cyberjaya City Centre MRT", kind: "train", distanceMetres: 1400 },
    { name: "Tamarind Square", kind: "mall", distanceMetres: 700 },
    { name: "Speedmart 99", kind: "mart", distanceMetres: 250 },
    { name: "Cyberjaya Lake Gardens", kind: "park", distanceMetres: 1200 },
    { name: "Cyberjaya Hospital", kind: "hospital", distanceMetres: 1600 },
  ],
  "shah-alam": [
    { name: "UiTM Shah Alam", kind: "uni", distanceMetres: 1100 },
    { name: "Padang Jawa KTM", kind: "train", distanceMetres: 1800 },
    { name: "Setia City Mall", kind: "mall", distanceMetres: 3200 },
    { name: "Mydin Section 7", kind: "mart", distanceMetres: 400 },
    { name: "Shah Alam Lake", kind: "park", distanceMetres: 2000 },
    { name: "Shah Alam Hospital", kind: "hospital", distanceMetres: 2700 },
  ],
  "subang-jaya": [
    { name: "Taylor's Lakeside", kind: "uni", distanceMetres: 800 },
    { name: "SS15 LRT", kind: "train", distanceMetres: 350 },
    { name: "Subang Parade", kind: "mall", distanceMetres: 1100 },
    { name: "Family Mart SS15", kind: "mart", distanceMetres: 80 },
    { name: "SS15 Park", kind: "park", distanceMetres: 500 },
    { name: "Subang Jaya Medical Centre", kind: "hospital", distanceMetres: 1300 },
  ],
  "bandar-sunway": [
    { name: "Sunway University canopy", kind: "uni", distanceMetres: 350 },
    { name: "Sunway-Setia Jaya BRT", kind: "train", distanceMetres: 600 },
    { name: "Sunway Pyramid", kind: "mall", distanceMetres: 700 },
    { name: "Family Mart Sunway", kind: "mart", distanceMetres: 100 },
    { name: "Sunway Lagoon Park", kind: "park", distanceMetres: 750 },
    { name: "Sunway Medical Centre", kind: "hospital", distanceMetres: 850 },
  ],
  cheras: [
    { name: "UCSI main building", kind: "uni", distanceMetres: 400 },
    { name: "Taman Connaught MRT", kind: "train", distanceMetres: 700 },
    { name: "Cheras Sentral", kind: "mall", distanceMetres: 1500 },
    { name: "Speedmart 99", kind: "mart", distanceMetres: 110 },
    { name: "Taman Connaught Park", kind: "park", distanceMetres: 600 },
    { name: "UCSI Hospital", kind: "hospital", distanceMetres: 800 },
  ],
  gombak: [
    { name: "IIUM Gombak gate", kind: "uni", distanceMetres: 1700 },
    { name: "Gombak LRT terminus", kind: "train", distanceMetres: 1200 },
    { name: "AEON Taman Maluri", kind: "mall", distanceMetres: 4500 },
    { name: "99 Speedmart", kind: "mart", distanceMetres: 220 },
    { name: "Bukit Lagong Forest Reserve", kind: "park", distanceMetres: 2800 },
    { name: "Selayang Hospital", kind: "hospital", distanceMetres: 5200 },
  ],
  setapak: [
    { name: "IIUM shuttle stop", kind: "uni", distanceMetres: 4500 },
    { name: "Sri Rampai LRT", kind: "train", distanceMetres: 900 },
    { name: "Setapak Central", kind: "mall", distanceMetres: 600 },
    { name: "99 Speedmart", kind: "mart", distanceMetres: 140 },
    { name: "Taman Tasik Permaisuri", kind: "park", distanceMetres: 1800 },
    { name: "Columbia Asia Setapak", kind: "hospital", distanceMetres: 1200 },
  ],
};
