import type { University } from "@/lib/types";

export const UNIVERSITIES: University[] = [
  {
    id: "um",
    name: "Universiti Malaya",
    shortName: "UM",
    city: "Kuala Lumpur",
    state: "WP Kuala Lumpur",
    lat: 3.1209,
    lng: 101.6538,
    studentCount: 22000,
    campusType: "public",
  },
  {
    id: "ukm",
    name: "Universiti Kebangsaan Malaysia",
    shortName: "UKM",
    city: "Bangi",
    state: "Selangor",
    lat: 2.9290,
    lng: 101.7780,
    studentCount: 27000,
    campusType: "public",
  },
  {
    id: "upm",
    name: "Universiti Putra Malaysia",
    shortName: "UPM",
    city: "Serdang",
    state: "Selangor",
    lat: 2.9889,
    lng: 101.7282,
    studentCount: 28000,
    campusType: "public",
  },
  {
    id: "uitm",
    name: "Universiti Teknologi MARA",
    shortName: "UiTM",
    city: "Shah Alam",
    state: "Selangor",
    lat: 3.0688,
    lng: 101.4985,
    studentCount: 180000,
    campusType: "public",
  },
  {
    id: "mmu",
    name: "Multimedia University",
    shortName: "MMU",
    city: "Cyberjaya",
    state: "Selangor",
    lat: 2.9270,
    lng: 101.6420,
    studentCount: 20000,
    campusType: "private",
  },
  {
    id: "sunway",
    name: "Sunway University",
    shortName: "Sunway",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0668,
    lng: 101.6038,
    studentCount: 16000,
    campusType: "private",
  },
  {
    id: "ucsi",
    name: "UCSI University",
    shortName: "UCSI",
    city: "Cheras",
    state: "WP Kuala Lumpur",
    lat: 3.0770,
    lng: 101.7320,
    studentCount: 12000,
    campusType: "private",
  },
  {
    id: "iium",
    name: "International Islamic University Malaysia",
    shortName: "IIUM",
    city: "Gombak",
    state: "Selangor",
    lat: 3.2528,
    lng: 101.7374,
    studentCount: 24000,
    campusType: "public",
  },
  {
    id: "taylors",
    name: "Taylor's University",
    shortName: "Taylor's",
    city: "Subang Jaya",
    state: "Selangor",
    lat: 3.0639,
    lng: 101.6175,
    studentCount: 14000,
    campusType: "private",
  },
  {
    id: "monash",
    name: "Monash University Malaysia",
    shortName: "Monash",
    city: "Bandar Sunway",
    state: "Selangor",
    lat: 3.0660,
    lng: 101.6005,
    studentCount: 8000,
    campusType: "private",
  },
];

export const UNIVERSITY_BY_ID = Object.fromEntries(
  UNIVERSITIES.map((u) => [u.id, u]),
) as Record<string, University>;
